```{r libs}
library(tidyverse)
library(ggplot2)
library(naturalsort)
library(Cairo)
analysis_date = "2017-06-16"
```

# Accuracy


```{r acc.data}
acc =  read.delim(paste0("results/", analysis_date, "/accuracy_summary.tsv"),
                  stringsAsFactors=F)

acc = acc %>%
    gather("Correctness", "Reads", -Seed, -Demuxer, -BarcodeSet) %>%
    separate(BarcodeSet, into=c("nidx", "index.length", "paired"), sep="-", remove=F) %>%
    mutate(BarcodeSet=naturalfactor(BarcodeSet), nidx=as.numeric(nidx))

acc.summ = acc %>%
    group_by(Demuxer, BarcodeSet, Correctness, nidx, paired) %>%
    summarise(reads.mean = mean(Reads),
              reads.sd = sd(Reads))
```

## Everything

```{r}
p = ggplot(acc, aes(x=Demuxer, y=Reads)) +
    geom_bar(aes(fill=Correctness), stat="identity") +
    scale_fill_brewer(palette = "Set1") +
    facet_wrap(~BarcodeSet, ncol = 4) + #, scales="free_x") +
    theme_bw()

print(p)
```

## Single end

```{r}
p = ggplot(filter(acc, paired=="se", index.length!="variable"), aes(x=Demuxer, y=Reads)) +
    geom_bar(aes(fill=Correctness), stat="identity") +
    scale_fill_brewer(palette = "Set1") +
    facet_wrap(~BarcodeSet, ncol = 4) + #, scales="free_x") +
    theme_bw()

svg("accuracy_se.svg", width=5, height=3)
print(p)
dev.off()
print(p)
```

## Combinatorial

```{r}
p = ggplot(filter(acc, paired=="pe", index.length!="variable"), aes(x=Demuxer, y=Reads)) +
    geom_bar(aes(fill=Correctness), stat="identity") +
    scale_fill_brewer(palette = "Set1") +
    facet_wrap(~BarcodeSet, ncol = 4) + #, scales="free_x") +
    theme_bw()

svg("accuracy_combo.svg", width=5, height=3)
print(p)
dev.off()
print(p)
```

## Variable-length

```{r}
p = ggplot(filter(acc, index.length == "variable"), aes(x=Demuxer, y=Reads)) +
    geom_bar(aes(fill=Correctness), stat="identity") +
    scale_fill_brewer(palette = "Set1") +
    facet_wrap(~BarcodeSet, ncol = 4) + #, scales="free_x") +
    theme_bw()

svg("accuracy_variable.svg", width=5, height=3)
print(p)
dev.off()
print(p)
```

## Summarised

This one goes in the paper

```{r}
acc.plot = filter(acc, index.length == "variable") %>%
    mutate(plot.group="variable")
acc.plot = filter(acc, index.length != "variable") %>%
    mutate(plot.group=paired) %>%
    bind_rows(acc.plot) %>%
    mutate(plot.group = factor(plot.group, levels=c("se", "pe", "variable"),
                               labels=c("Single-end", "Comb.", "Var.")),
           Demuxer = factor(Demuxer, levels=c("axe", "ar", "fastx", "flexbar"),
                            labels=c("Axe", "AR", "Fastx", "FlexBar")),
           Correctness = factor(Correctness, levels=c("Incorrect", "Unassigned", "Correct")))


acc.total = acc.plot %>%
    group_by(Demuxer, plot.group, Correctness) %>%
    summarise(reads=sum(Reads)) %>%
    left_join(acc.plot %>% group_by(Demuxer, plot.group) %>% summarise(total_reads=sum(Reads))) %>%
    mutate(reads.prop = reads/total_reads,
           reads.pct = reads.prop * 100) %>%
    select(-total_reads)
acc.wrong = acc.total %>% filter(Correctness != "Correct")
acc.total
```

```{r}
acc.fill.scale = scale_fill_manual(values=c("#E41A1C", "#66A8CF", "#66C2A5"))

p = ggplot(acc.wrong, aes(x=Demuxer, y=reads.pct)) +
    geom_bar(aes(fill=Correctness), stat="identity") +
    acc.fill.scale +
    facet_grid(~plot.group, scales="free_x", space="free_x") +
    labs(y="Percent of all reads", y="Demultiplexer") +
    theme_bw() +
    theme(axis.text.x = element_text(angle=45, hjust=1))

svg("accuracy_pct.svg", width=5, height=3)
print(p)
dev.off()
print(p)
```


```{r}
p = ggplot(acc.total, aes(x=Demuxer, y=reads.pct)) +
    geom_bar(aes(fill=Correctness), stat="identity") +
    acc.fill.scale +
    facet_grid(~plot.group, scales="free_x", space="free_x") +
    labs(y="Percent of all reads", y="Demultiplexer") +
    theme_bw() +
    theme(axis.text.x=element_text(angle=45, hjust=1))

svg("accuracy_total.svg", width=4, height=3)
print(p)
dev.off()
pdf("accuracy_total.pdf", width=4, height=3)
print(p)
dev.off()
print(p)
```


# Timing


```{r load.timing}
timing = read.delim(paste0("results/", analysis_date, "/timing_summary.tsv"),
                    stringsAsFactors=T) %>%
    separate(BarcodeSet, into=c("nidx", "index.length", "paired"), sep="-", remove=F) %>%
    mutate(BarcodeSet=naturalfactor(BarcodeSet), nidx=as.numeric(nidx)) %>%
    filter(nidx <=10000) %>%
    filter(index.length != "variable") %>%
    mutate(paired = factor(paired, levels=c("se", "pe"),
                           labels=c("Single-end", "Combinatorial")),
           Demuxer = factor(Demuxer, levels=c("axe", "ar", "fastx", "flexbar"),
                            labels=c("Axe", "AR", "Fastx", "FlexBar")))

timing.summ = timing %>%
    group_by(Demuxer, BarcodeSet, nidx, paired) %>%
    summarise(time.mean = mean(Sec), time.sd = sd(Sec))
```


```{r}
p = ggplot(filter(timing.summ, paired=="Single-end"), aes(x=Demuxer, y=time.mean)) +
    geom_bar(aes(fill=Demuxer), stat="identity") +
    geom_errorbar(aes(ymin=time.mean-time.sd, ymax=time.mean+time.sd)) +
    scale_fill_brewer(palette = "Set1") +
    facet_wrap(~BarcodeSet, ncol=3) +
    theme_bw()

print(p)
```


```{r}
p = ggplot(filter(timing.summ, paired=="Combinatorial"), aes(x=Demuxer, y=time.mean)) +
    geom_bar(aes(fill=Demuxer), stat="identity") +
    geom_errorbar(aes(ymin=time.mean-time.sd, ymax=time.mean+time.sd)) +
    scale_fill_brewer(palette = "Set1") +
    facet_wrap(~BarcodeSet, ncol=3) +
    theme_bw()

print(p)
```


```{r}
p = ggplot(timing.summ, aes(x=nidx, y=time.mean)) +
    geom_line(aes(linetype=Demuxer)) +
    geom_ribbon(aes(ymin=time.mean-time.sd, ymax=time.mean+time.sd, colour=Demuxer, fill=Demuxer), alpha=0.2) +
    facet_wrap(~paired, scales = "free")  +
    ylab("Time (s/million reads)") +
    xlab("Number of Samples") +
    theme_bw()

svg("timing.svg", width=5,height=3)
print(p)
dev.off()
pdf("timing.pdf", width=5,height=3)
print(p)
dev.off()
print(p)
```


```{r}
p = ggplot(timing.summ, aes(x=nidx, y=time.mean)) +
    geom_line(aes(linetype=Demuxer)) +
    geom_ribbon(aes(ymin=time.mean-time.sd, ymax=time.mean+time.sd, colour=Demuxer, fill=Demuxer), alpha=0.2) +
    facet_wrap(~paired, scales = "free")  +
    ylab("Time (s/million reads)") +
    xlab("Number of Samples") +
    scale_y_log10() +
    scale_x_log10() +
    theme_bw()

svg("timing_log.svg", width=5,height=3)
print(p)
dev.off()
print(p)
```
